/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Modelo.Tractor;
import Modelo.Truck;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.Semaphore;
import javax.swing.ImageIcon;

/**
 *
 * @author rubco
 */
public class CochesPanel extends javax.swing.JPanel {

    private List<Image> camiones;
    private List<Image> camionesR;
    private List<Image> tractores;
    private List<Image> tractoresR;
    private Object[] fases;
    private List<Object> hilos;

    /**
     * Creates new form cochesPanel
     */
    public CochesPanel(Object[] fases, List<Object> hilos) {
        initComponents();
        setOpaque(false);

        this.fases = fases;
        this.hilos = hilos;
        camiones = new ArrayList<>();
        camionesR = new ArrayList<>();
        tractores = new ArrayList<>();
        tractoresR = new ArrayList<>();

        camiones.add(new ImageIcon(getClass().getResource("/imagenes/camion1.png")).getImage());
        camiones.add(new ImageIcon(getClass().getResource("/imagenes/camion2.png")).getImage());
        camiones.add(new ImageIcon(getClass().getResource("/imagenes/camion3.png")).getImage());
        camiones.add(new ImageIcon(getClass().getResource("/imagenes/camion4.png")).getImage());
        camiones.add(new ImageIcon(getClass().getResource("/imagenes/camion5.png")).getImage());

        camionesR.add(new ImageIcon(getClass().getResource("/imagenes/camion1R.png")).getImage());
        camionesR.add(new ImageIcon(getClass().getResource("/imagenes/camion2R.png")).getImage());
        camionesR.add(new ImageIcon(getClass().getResource("/imagenes/camion3R.png")).getImage());
        camionesR.add(new ImageIcon(getClass().getResource("/imagenes/camion4R.png")).getImage());
        camionesR.add(new ImageIcon(getClass().getResource("/imagenes/camion5R.png")).getImage());

        tractores.add(new ImageIcon(getClass().getResource("/imagenes/tractor1.png")).getImage());
        tractores.add(new ImageIcon(getClass().getResource("/imagenes/tractor2.png")).getImage());
        tractores.add(new ImageIcon(getClass().getResource("/imagenes/tractor3.png")).getImage());
        tractores.add(new ImageIcon(getClass().getResource("/imagenes/tractor4.png")).getImage());
        tractores.add(new ImageIcon(getClass().getResource("/imagenes/tractor5.png")).getImage());

        tractoresR.add(new ImageIcon(getClass().getResource("/imagenes/tractor1R.png")).getImage());
        tractoresR.add(new ImageIcon(getClass().getResource("/imagenes/tractor2R.png")).getImage());
        tractoresR.add(new ImageIcon(getClass().getResource("/imagenes/tractor3R.png")).getImage());
        tractoresR.add(new ImageIcon(getClass().getResource("/imagenes/tractor4R.png")).getImage());
        tractoresR.add(new ImageIcon(getClass().getResource("/imagenes/tractor5R.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody

        setPreferredSize(new Dimension(1500, 1000));

        Graphics2D g2d = (Graphics2D) g;
        g2d.setRenderingHint(
                RenderingHints.KEY_ANTIALIASING,
                RenderingHints.VALUE_ANTIALIAS_ON
        );

        g2d.setColor(new Color(255, 0, 0));
        g2d.setFont(new Font("Segoe UI", Font.BOLD, 20));

        for (int i = 0; i < 3; i++) {
            if (fases[i] == null) {
                continue;
            }
            if (fases[i] instanceof Truck) {
                Truck cam = (Truck) fases[i];
                g2d.drawImage(camiones.get(cam.getIdent() % 5), 1040 - (i * 240), 370, 200, 175, this);

                g2d.drawString("" + cam.getIdent(), 1065 - (i * 240), 450);
            } else {
                Tractor trac = (Tractor) fases[i];
                g2d.drawImage(tractores.get(trac.getIdent() % 5), 1035 - (240 * i), 355, 450, 175, this);

                g2d.drawString("" + trac.getIdent(), 1065 - (i * 240), 450);
            }
        }

        int colaTractores = 0;
        int colaCamiones = 0;

        for (Object hilo : hilos) {
            if (hilo instanceof Truck) {
                Truck cam = (Truck) hilo;
                if (cam.isFinish() || cam.getEstado() != -1 || colaCamiones == 8) {
                    continue;
                }

                g2d.drawImage(camionesR.get(cam.getIdent() % 5), 1300 - (colaCamiones * 250), 545, 200, 175, this);
                g2d.drawString("" + cam.getIdent(), 1480 - (colaCamiones * 250), 595);
                colaCamiones++;
            } else {
                Tractor trac = (Tractor) hilo;
                if (trac.isFinish() || trac.getEstado() != -1 || colaTractores == 4) {
                    continue;
                }
                g2d.drawImage(tractoresR.get(trac.getIdent() % 5), 1080 - (400 * colaTractores), 735, 450, 175, this);
                g2d.drawString("" + trac.getIdent(), 1480 - (colaTractores * 400), 795);
                colaTractores++;
            }
        }

    }

    //Camiones primer terminal g2d.drawImage(camiones.get(4),1040, 370, 200, 175, this);
    //Camiones segundo terminal g2d.drawImage(camiones.get(0),800, 370, 200, 175, this);
    //Camiones tercer Terminal g2d.drawImage(camiones.get(0),560, 370, 200, 175, this);
    //Tractores tercer terminal g2d.drawImage(tractores.get(4),565, 355, 450, 175, this); 
    //Tractores segundo terminal g2d.drawImage(tractores.get(2),795, 355, 450, 175, this);
    //Tractores primer terminal g2d.drawImage(tractores.get(4),1035, 355, 450, 175, this);
    //Cola de camiones g2d.drawImage(camionesR.get(4),1300, 545, 200, 175, this);
    //Cola de camiones g2d.drawImage(camionesR.get(0),1050, 545, 200, 175, this);
    // -250
    //Cola de tractores g2d.drawImage(tractoresR.get(0),1080, 735, 450, 175, this);
    //Cola de tractores g2d.drawImage(tractoresR.get(1),680, 735, 450, 175, this);
    //Cola de tractores g2d.drawImage(tractoresR.get(2),280, 735, 450, 175, this);
    //Cola de tractores g2d.drawImage(tractoresR.get(3),280 -400, 735, 450, 175, this);
    // -400

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
