/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import javax.swing.ImageIcon;

/**
 *
 * @author rubco
 */
public class FondoPanel extends javax.swing.JPanel {
    
    private final Image granja;
    private final Image nubes;
    private final Image casetas;
    
    /**
     * Creates new form FondoPanel
     */
    public FondoPanel() {
        initComponents();
        setOpaque(false);
        granja = new ImageIcon(getClass().getResource("/imagenes/granja.png")).getImage();
        nubes = new ImageIcon(getClass().getResource("/imagenes/nubes.png")).getImage();
        casetas = new ImageIcon(getClass().getResource("/imagenes/caseta.png")).getImage();
    }
    
    
    @Override
    protected void paintComponent(Graphics g){
        super.paintComponent(g);
        
        setPreferredSize(new Dimension(1000, 700));

        Graphics2D g2d = (Graphics2D) g;
        g2d.setRenderingHint(
                RenderingHints.KEY_ANTIALIASING,
                RenderingHints.VALUE_ANTIALIAS_ON
        );
        //cielo
        g2d.setColor(new Color(66, 199, 244));
        g2d.fillRect(0, 0, 1500, 401);
        //tierra
        g2d.setColor(new Color(141, 201, 103));
        g2d.fillRect(0, 400, 1500, 600);
        //granja
        g2d.drawImage(granja, 0, 0, 500, 470,this);
        //nubes
        g2d.drawImage(nubes, 500, 70,250, 225,this);
        g2d.drawImage(nubes, 1000, 20,200, 175,this);
        //carreteras
        g2d.setColor(new Color(75, 97, 111));
        g2d.fillRect(200, 445, 1300, 100);
        g2d.fillRect(0, 600, 1500, 125);
        g2d.fillRect(0, 800, 1500, 140);
        //lineas carretera
        g2d.setColor(new Color(255, 251, 242));
        g2d.fillRect(300, 452, 1300, 5);
        g2d.fillRect(200, 533, 1300, 6);
        
        g2d.fillRect(0, 607, 1500, 7);
        g2d.fillRect(0, 707, 1500, 8);
        
        g2d.fillRect(0, 807, 1500, 9);
        g2d.fillRect(0, 919, 1500, 10);
        
        //casetas
        g2d.drawImage(casetas, 520, 220, 320,320,this);
        g2d.drawImage(casetas, 750, 220, 320,320,this);
        g2d.drawImage(casetas, 980, 220, 320,320,this);
        
        g2d.setFont(new Font("Segoe UI", Font.BOLD, 18));
        g2d.drawString("Documentación", 608, 300);
        g2d.drawString("Descarga", 870, 300);
        g2d.drawString("Preadmisión", 1090, 300);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
